spring.application.name=BankingProject


# H2 Database Connection
spring.datasource.url=jdbc:h2:mem:banking_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Tell Hibernate to automatically create our tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable the built-in H2 Web Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true
